from tkinter import *
from datetime import datetime
t1=datetime.now()
t=datetime.strftime(t1,'%d/%m/%Y %H:%M:%S %p')
w=Tk()
w.geometry('500x500')
def getvals():
    
    f2=open('Dance Ragister.txt','a')
    f2.write(f"\n\n Name = {Name.get()}")
    f2.write(f'\nClass = {Class.get()}')
    f2.write(f'\nBranch = {Branch.get()}')
    f2.write(f'\nRegd. no = {Regd.get()}')
    f2.write(f'\nEntering Date and time = {t}')
    f2.close()
    print('Your data has been Printed Please log out .')
Label(text='Name ',font=50).grid()
Label(text='Class ',font=50).grid()
Label(text='Branch ',font=50).grid()
Label(text='Regd. No ',font=50).grid()
Name=StringVar()
Class=StringVar()
Branch=StringVar()
Regd=StringVar()
Entry(textvariable=Name).grid(row=0,column=1)
Entry(textvariable=Class).grid(row=1,column=1)
Entry(textvariable=Branch).grid(row=2,column=1)
Entry(textvariable=Regd).grid(row=3,column=1)
Button(text='Submit',font=50,borderwidth=5,bg='black',fg='white',command=getvals).grid()
w.mainloop()